export const ticker = [
  "No to big brands that cut corners",
  "No to fruit lacking sweetness and crunch",
  "No to eggs that skip lab tests",
  "No to milk with growth hormones",
  "No to veg that arrives wilted and bruised",
  "No to sugar hiding behind other names",
  "No to palm oil dressed up as vegetable oil",
  "No to juice that is mostly sugar syrup",
];

export const gates = [
  { n: "01", q: "Is this worth evaluating?", status: "Passed", state: "done" },
  { n: "02", q: "Does it meet scientific standards?", status: "Passed", state: "done" },
  { n: "03", q: "Can we trust the supplier?", status: "Checking", state: "active" },
  { n: "04", q: "Would our experts recommend it?", status: "Up next", state: "next" },
];

export const categories = [
  { name: "Nut butter", src: "/photos/figma/nut-butter.svg" },
  { name: "Oats", src: "/photos/figma/oats.svg" },
  { name: "Porridge", src: "/photos/figma/porridge.svg" },
  { name: "Chia seeds", src: "/photos/figma/chia.svg" },
  { name: "Chips & crisps", src: "/photos/figma/crisps.svg" },
  { name: "Energy bars", src: "/photos/energy-bars.jpg" },
  { name: "Chocolates", src: "/photos/figma/chocolates.svg" },
  { name: "Protein bars", src: "/photos/figma/protein-bars.svg" },
  { name: "Peanuts", src: "/photos/figma/peanuts.svg" },
  { name: "Soda", src: "/photos/soda.jpg" },
  { name: "Juices", src: "/photos/figma/juices.svg" },
  { name: "Electrolytes", src: "/photos/electrolytes.jpg" },
  { name: "Pulses", src: "/photos/pulses.jpg" },
  { name: "Cooking oil", src: "/photos/cooking-oil.jpg" },
  { name: "Pasta", src: "/photos/pasta.jpg" },
  { name: "Khapli atta", src: "/photos/atta.jpg" },
  { name: "Sauces & spreads", src: "/photos/sauces.jpg" },
];

export const bans = [
  {
    id: "sugars",
    n: "01",
    label: "Sugars",
    title: "Hidden sugars",
    src: "/photos/figma/ban-sugars.svg",
    tint: "#F8EADB",
    chips: ["Maltodextrin", "Invert syrup", "Dextrose", "High-fructose corn syrup"],
    why: "Sugar under another name, listed low enough that “sugar” never appears near the top.",
    found: "Cereals, flavoured yoghurt, bars, sauces.",
    alt: "Hidden sugars. Maltodextrin, invert syrup, dextrose, and high-fructose corn syrup. Found in cereals, flavoured yoghurt, bars, and sauces.",
  },
  {
    id: "fats",
    n: "02",
    label: "Fats",
    title: "Disguised fats",
    src: "/photos/figma/ban-fats.svg",
    tint: "#C9E3CE",
    chips: ["Palm oil", "Palm olein", "Hydrogenated fats", "Interesterified fats"],
    why: "Hidden behind “vegetable oil”. We ask for the oil, named.",
    found: "Biscuits, noodles, spreads, bakery fats.",
    alt: "Disguised fats. Palm oil, palm olein, hydrogenated fats, and interesterified fats. Found in biscuits, noodles, spreads, and bakery fats.",
  },
  {
    id: "hormones",
    n: "03",
    label: "Hormones",
    title: "Growth hormones",
    src: "/photos/figma/ban-hormones.svg",
    tint: "#D3E5F3",
    chips: ["rBST", "rBGH"],
    why: "Raises yield, not quality. Suppliers declare it; we test against the declaration.",
    found: "Undeclared or untested dairy.",
    alt: "Growth hormones. rBST and rBGH in undeclared or untested dairy.",
  },
  {
    id: "sweeteners",
    n: "04",
    label: "Sweeteners",
    title: "Artificial sweeteners",
    src: "/photos/figma/ban-sweeteners.svg",
    tint: "#C9E3CE",
    chips: ["Aspartame (E951)", "Sucralose (E955)", "Acesulfame K (E950)", "Saccharin (E954)"],
    why: "Sweeter and cheaper than sugar. We would rather it were simply less sweet.",
    found: "Diet drinks, sugar-free sweets, protein powders.",
    alt: "Artificial sweeteners. Aspartame, sucralose, acesulfame K, and saccharin. Found in diet drinks, sugar-free sweets, and protein powders.",
  },
  {
    id: "preservatives",
    n: "05",
    label: "Preservatives",
    title: "Synthetic preservatives",
    src: "/photos/figma/ban-preservatives.svg",
    tint: "#D3E5F3",
    chips: ["Sodium benzoate (E211)", "BHA (E320)", "BHT (E321)", "Sodium nitrite (E250)"],
    why: "Shelf life is our problem, not yours.",
    found: "Soft drinks, bread, cured meats, sauces.",
    alt: "Synthetic preservatives. Sodium benzoate, BHA, BHT, and sodium nitrite. Found in soft drinks, bread, cured meats, and sauces.",
  },
  {
    id: "colours",
    n: "06",
    label: "Colours",
    title: "Artificial colours",
    src: "/photos/figma/ban-colours.svg",
    tint: "#F8EADB",
    chips: ["Tartrazine (E102)", "Sunset Yellow (E110)", "Carmoisine (E122)", "Ponceau 4R (E124)"],
    why: "Added to make food look like something it isn’t.",
    found: "Sweets, soft drinks, icing, savoury snacks.",
    alt: "Artificial colours. Tartrazine, Sunset Yellow, Carmoisine, and Ponceau 4R. Found in sweets, soft drinks, icing, and savoury snacks.",
  },
];

export const comparisons = [
  {
    name: "Sauce",
    src: "/photos/figma/cmp-sauce.svg",
    crop: 400,
    offset: false,
    pass: ["Made from real tomatoes", "Visible chunks, seeds and herbs", "Richer, more natural flavour"],
    fail: ["Highly processed and refined", "May contain additives and preservatives", "Milder taste and uniform texture"],
  },
  {
    name: "Peanut butter",
    src: "/photos/figma/cmp-peanut.svg",
    crop: 340,
    offset: true,
    pass: ["Real peanuts with natural texture", "No artificial additives", "Rich, nutty flavour"],
    fail: ["Processed and refined", "Added oils and sugar", "Smooth but less nutritious"],
  },
  {
    name: "Dark chocolate",
    src: "/photos/figma/cmp-chocolate.svg",
    crop: 360,
    offset: false,
    pass: ["Rich, natural cocoa", "No artificial additives", "Deep, intense flavour"],
    fail: ["Added oils and sugar", "Artificial additives", "Pale and overly sweet"],
  },
  {
    name: "Crisps",
    src: "/photos/figma/cmp-crisps.svg",
    crop: 380,
    offset: false,
    pass: ["Made from real potatoes with skin", "Naturally cooked and less processed", "Richer flavour and satisfying crunch"],
    fail: ["Uniform, machine-made shape", "Highly processed and refined", "Milder taste and less natural texture"],
  },
  {
    name: "Energy bars",
    src: "/photos/figma/cmp-energy.svg",
    crop: 380,
    offset: true,
    pass: ["Whole dates, nuts and real ingredients", "No artificial additives", "Naturally sweet delicious taste"],
    fail: ["Processed, uniform paste", "Artificial additives", "Flat and overly sweet"],
  },
  {
    name: "Oil",
    src: "/photos/figma/cmp-oil.svg",
    crop: 360,
    offset: false,
    pass: ["Natural and unfiltered", "Retains natural nutrients and flavour", "Minimal processing"],
    fail: ["Highly processed and refined", "Nutrients removed", "Neutral taste and aroma"],
  },
];

export const pillars = [
  {
    src: "/photos/figma/img-011322-am-1.svg",
    kicker: "Choose better",
    title: "What goes in the basket matters.",
    body: "We choose products for what is actually in them, not for what the front of the pack says.",
    cta: "See our standard",
    alt: "Choose better. What goes in the basket matters. We choose products for what is actually in them, not for what the front of the pack says.",
    href: "/#vet",
    image_position: "object-[50%_center]",
  },
  {
    src: "/photos/figma/img-011306-am-1.svg",
    kicker: "Know better",
    title: "Good food starts with a good label.",
    body: "Every product is checked past the claim — ingredients, nutrition, sourcing and lab results.",
    cta: "What we check",
    alt: "Know better. Good food starts with a good label. Every product is checked past the claim — ingredients, nutrition, sourcing and lab results.",
    href: "/#bans",
    image_position: "object-[55%_center]",
  },
  {
    src: "/photos/figma/img-011302-am-1.svg",
    kicker: "Feel better",
    title: "Less guesswork. More good food.",
    body: "No label decoding, no endless comparison. If it is on Sortd, it already passed.",
    cta: "Browse the shelf",
    alt: "Feel better. Less guesswork. More good food. If it is on Sortd, it already passed.",
    href: "/#products",
    image_position: "object-[50%_center]",
  },
];
